// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className=" min-h-screen antialiased">
        {/* Navbar at the top */}
        <Navbar className="mx-auto w-full max-w-4xl px-8" />

        {/* Main grows to push footer down */}
        {children}

        {/* Footer always sticks at bottom */}
        <Footer />
      </body>
    </html>
  );
}
